Add llvmdev and clangdev to host directive
conda-forge/hoomd-feedstock pull request #65
Opened 2022-05-06 15:19 UTC by tcmoore3

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-05-06 15:19 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-05-06 15:35 UTC, b-butler approved these changes

2022-05-09 14:53 UTC, joaander commented
@conda-forge-admin, please restart ci

2022-05-15 04:39 UTC, tcmoore3 commented
The upstream issue is addressed in glotzerlab/hoomd-blue#1321

2022-05-16 12:52 UTC, joaander requested changes
Changes needed after the v3.2.0 release.

2022-05-16 12:52 UTC, joaander commented on recipe/meta.yaml
> +{% set build = 1 %}
```suggestion
{% set build = 0 %}
```

2022-05-16 12:52 UTC, joaander commented on recipe/meta.yaml
> +  git_rev: fix/find-clang
```suggestion
 fn: {{ name }}-{{ version }}.tar.gz
 url: https://github.com/glotzerlab/hoomd-blue/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
 sha256: {{ sha256 }}
```

2022-05-16 12:52 UTC, joaander commented on recipe/meta.yaml
>  {% set version = "3.1.0" %}
```suggestion
{% set version = "3.2.0" %}
```

2022-05-16 12:52 UTC, joaander commented on recipe/meta.yaml
>  {% set sha256 = "4a83d3d6098f07cb0deaacd2953998abeb111aad98fe5a0eb9403001d58d704c" %}
Set the correct sha256 after the v3.2.0 release tarball is uploaded.

2022-05-18 16:54 UTC, joaander requested changes
No need to remove spaces.

2022-05-18 16:54 UTC, joaander commented on recipe/meta.yaml
> + sha256: {{ sha256 }}
```suggestion
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/glotzerlab/hoomd-blue/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}
```

2022-05-18 17:39 UTC, joaander commented
@conda-forge-admin, please rerender

2022-05-18 18:54 UTC, joaander approved these changes
Thanks!

2022-05-18 19:20 UTC, merged